### PR TITLE
Disable building wheels for main requirements

### PR DESCRIPTION
**Pull request by kosmos342**
We have problems with building some wheel packages

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by Toshakins** [comment]
I thought `--no-binary` **enables** building wheels instead of using binary packages. Correct?

**Comment by kosmos342** [comment]
> I thought `--no-binary` **enables** building wheels instead of using binary packages. Correct?

We have no wheel packages in our custom repository. Without this option, we build wheel packages  from sources and save them into the cache(as I understand)

**Comment by stefanor** [comment]
That's going to make builds take a lot longer. We cache wheels purposely.

**Comment by kosmos342** [comment]
problem was with broken cache

**Pull request closed without merging**
