### PR TITLE
Revert always upgrade pip due to bug

### PR DESCRIPTION
**Pull request by fr33l**
Currently new virtualenvs are failing with:

```
INFO:yodeploy.virtualenv.pip:Getting requirements to build wheel: started
INFO:yodeploy.virtualenv.pip:Getting requirements to build wheel: finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "/mnt/jenkins-workspaces/yodeploy/deploy/virtualenv/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/mnt/jenkins-workspaces/yodeploy/deploy/virtualenv/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/mnt/jenkins-workspaces/yodeploy/deploy/virtualenv/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/mnt/jenkins-workspaces/yodeploy/deploy/virtualenv/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/mnt/jenkins-workspaces/yodeploy/deploy/virtualenv/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/mnt/jenkins-workspaces/yodeploy/deploy/virtualenv/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 362, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/mnt/jenkins-workspaces/yodeploy/deploy/virtualenv/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 169, in prep_for_dist
    self.install_backend_dependencies(finder=finder)
  File "/mnt/jenkins-workspaces/yodeploy/deploy/virtualenv/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 123, in install_backend_dependencies
    reqs = req.pep517_backend.get_requires_for_build_wheel()
  File "/mnt/jenkins-workspaces/yodeploy/deploy/virtualenv/local/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 71, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/mnt/jenkins-workspaces/yodeploy/deploy/virtualenv/local/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 162, in _call_hook
    raise BackendUnavailable
BackendUnavailable
ERROR:yodeploy.virtualenv:pip exited non-zero (2)
build-virtualenv failed
```

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by kosmos342** [comment]
I tried to reproduce the problem on int env with custom `yodeploy` branch(where was reverted you revert). It was not successful. Do you remember with which service was the problem(except `yodeploy`)?

**Comment by stefanor** [comment]
Triggered virtualenv rebuilds of everything on your env. Looks like most of them are failing :)

**Comment by kosmos342** [comment]
cool:) How can I do it myself?

**Comment by stefanor** [comment]
Something like:
```
rm -rf /var/lib/jenkins/workspaces/*/virtualenv{,.tar.gz}
rm -rf /srv/deploy/data/artifacts/*/master/virtualenv*
```

**Pull request merged**
