### PR TITLE
bump version to 0.7.2

### PR DESCRIPTION
**Pull request by jamesodo**
yodeploy is now compatible with django 1.9+

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by RayeN** [comment]
Changes are backwards compatible, right?

**Comment by jamesodo** [comment]
I guess they could be considered backward compatible but I would argue that supporting a new version of Django isn't a bug fix.

**Comment by RayeN** [comment]
Right, it's a new functionality, but we're in a dev mode < 1.0.0.  And for that mode AFAIR we agreed to increment patch version for backwards compatible changes and minor version for incompatible ones.

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Pull request merged**
